title: CUSO Graduate Colloquium 2024
preposition: at
description: >-
  Where PhD students present their research topic to fellow students.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://example.com" # the base hostname & protocol for your site, e.g. https://example.com

# theme: jekyll-theme-conference

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js
  - build.sh

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: Cuso Graduate Colloquium
      img: 'logos_cuso/cuso_graduate_colloquium_tiny.png'
      url: 'https://math.cuso.ch/colloquium/graduate-colloquium'
    breakpoint: md
    links:
      - name: Register
        relative_url: /register/
        disabled: false
      - name: Program
        relative_url: /program/
        disabled: true
      - name: Talks
        relative_url: /talks/
        disabled: true
      - name: Speakers
        relative_url: /speakers/
        disabled: true
      - name: Location
        relative_url: /location/
      - name: Previous Editions
        menu:
          - name: 2024 (current)
            disabled: true
          - name: 2023
            absolute_url: https://commonweb.unifr.ch/math/Pub/cuso/colloquium/index.html
          - name: others
            absolute_url: https://math.cuso.ch/colloquium/graduate-colloquium

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    logo:
      img: 'logos_cuso/cuso_graduate_colloquium.png'
    links:
      - name: Register
        relative_url: /register/
        disabled: false
      - name: Program
        relative_url: /program/
        disabled: true

  # Information boxes
  info_bars:
    - title: Registration is open now!
      color: info
      main_only: true
      text: |
        You may register for the CUSO Graduate Colloquium now [here](/register).
        The 2024 edition of the yearly CUSO Graduate Colloquium will take place in Bern for the first time since 2015.

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      - name: Cat A
        color: info
      - name: Cat B
        color: success

    # Hide icons on talk overview page
    hide_icons: true

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: 46.95404119907899, 7.438369274824375
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 19


  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
